name: Bloodline's Blog
url: 'http://www.ibloodline.com'
description: 'Notes and thoughts from Bloodline'

exclude: [Gemfile, Gemfile.lock, README.md]
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]

author: 'Tony Han'
disqus_shortname: Bloodline
google_analytics: UA-73798612-1

gems:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap

paginate: 5 # 指定每页多少条
paginate_path: "page:num" # 指定每页的url

sass:
    sass_dir: _sass
    style: :compressed

disqus_shortname : ibloodline

timezone: Asia/Shanghai

encoding : utf-8